name: release

on:
  push:
    tags:
      - '*.*.*'

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - run: |
          IS_PRERELEASE=false
          if [[ $GITHUB_REF_NAME =~ 'alpha' || $GITHUB_REF_NAME =~ 'beta' || $GITHUB_REF_NAME =~ 'rc' ]]; then
            IS_PRERELEASE=true
          fi
          echo "IS_PRERELEASE=$IS_PRERELEASE" >> $GITHUB_ENV

      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref }}
          name: v${{ github.ref_name }}
          body: Please refer to [CHANGELOG.md](https://github.com/${{ github.repository }}/blob/${{ github.ref_name }}/CHANGELOG.md) for details.
          draft: false
          prerelease: ${{ env.IS_PRERELEASE }}
