name: Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v5

      - name: PHPCS
        run: composer run phpcs

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

      - uses: php-actions/composer@v5

      - name: PHPStan
        run: composer run phpstan

  test:
    name: Unit test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.0]
    steps:
      - uses: actions/checkout@v2

      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}-${{ matrix.php }}

      - uses: php-actions/composer@v5
        with:
          php_version: ${{ matrix.php }}

      - name: Pest
        run: ./vendor/bin/pest --coverage --coverage-clover='coverage.xml'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          fail_ci_if_error: true
          path_to_write_report: ./codecov_report.txt
          verbose: true
